site_name: PaReco
site_description: Patched clones and missed patches among the divergent variants of a software family
site_url: ""
copyright: Copyright &copy; 2022 - 2023 SEVOL UNLV
theme:
  name: material
# extra:
#   copyright: Copyright &copy; 2016 - 2020 Martin Donath
nav:
    - Overview: index.md
    - Getting Started: about.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unlv-evol/PaReco
      name: GitHub

