site_name: PaReco
site_description: Patched clones and missed patches among the divergent variants of a software family
site_url: ""
copyright: Copyright &copy; 2022 - 2023 SEVOL UNLV
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/unlv-evol/PaReco
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/unlv-evol
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/unlv-evol
nav:
    - Overview: index.md
    - Getting Started: about.md

